name: Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  unittest:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ['3.10', '3.12', '3.14']
        include:
          - os: windows-latest
            python: '3.12'
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python }}
      - run: python -m unittest discover -v
